config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :alumnis
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   root "alumnis#index"
end

app/models/alumni.rb
class Alumni < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/alumnis_controller.rb
class AlumnisController < ApplicationController
  before_action :set_alumni, only: %i[ show edit update destroy ]

  # GET /alumnis or /alumnis.json
  def index
    @alumnis = Alumni.all
  end

  # GET /alumnis/1 or /alumnis/1.json
  def show
  end

  # GET /alumnis/new
  def new
    @alumni = Alumni.new
  end

  # GET /alumnis/1/edit
  def edit
  end

  # POST /alumnis or /alumnis.json
  def create
    @alumni = Alumni.new(alumni_params)

    respond_to do |format|
      if @alumni.save
        format.html { redirect_to @alumni, notice: "Alumni was successfully created." }
        format.json { render :show, status: :created, location: @alumni }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @alumni.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnis/1 or /alumnis/1.json
  def update
    respond_to do |format|
      if @alumni.update(alumni_params)
        format.html { redirect_to @alumni, notice: "Alumni was successfully updated." }
        format.json { render :show, status: :ok, location: @alumni }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @alumni.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnis/1 or /alumnis/1.json
  def destroy
    @alumni.destroy!

    respond_to do |format|
      format.html { redirect_to alumnis_path, status: :see_other, notice: "Alumni was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumni
      @alumni = Alumni.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def alumni_params
      params.expect(alumni: [ :first_name, :last_name, :email ])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/alumnis_helper.rb
module AlumnisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alumnis/_alumni.html.erb
<tr>
  <td class="px-4 py-3">
    <div class="flex items-center space-x-3">
      <div>
        <%= link_to alumni.first_name + " " + alumni.last_name, alumni_path(alumni), class: "hover:underline cursor-pointer text-gray-900 dark:text-white font-medium" %>
      </div>
    </div>
  </td>
  <td class="px-4 py-3">
    <%= alumni.email %>
  </td>
</tr>

app/views/alumnis/_form.html.erb
<%= form_with(model: alumni, class: "contents") do |form| %>
  <% if alumni.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(alumni.errors.count, "error") %> prohibited this alumni from being saved:</h2>

      <ul class="list-disc ml-6">
        <% alumni.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": alumni.errors[:first_name].none?, "border-red-400 focus:outline-red-600": alumni.errors[:first_name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": alumni.errors[:last_name].none?, "border-red-400 focus:outline-red-600": alumni.errors[:last_name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": alumni.errors[:email].none?, "border-red-400 focus:outline-red-600": alumni.errors[:email].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/alumnis/edit.html.erb
<% content_for :title, "Editing alumni" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing alumni</h1>

  <%= render "form", alumni: @alumni %>

  <%= link_to "Show this alumni", @alumni, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to alumnis", alumnis_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/alumnis/index.html.erb
<% content_for :title, "Alumnis" %>
<%= render "shared/nav"%>

<section class="bg-gray-50 dark:bg-gray-900 py-3 sm:py-5 min-h-screen">
  <div class="px-4 mx-auto max-w-screen-2xl lg:px-8">
    <div class="relative overflow-hidden bg-white shadow-md dark:bg-gray-800 sm:rounded-sm">
      <div class=" divide-y dark:divide-gray-700">
        <div class="flex-row items-center justify-between p-4 space-y-3 sm:flex sm:space-y-0 sm:space-x-4">
          <div>
            <h1 class="mr-3 text-lg font-semibold dark:text-white">Alumni</h1>
            <p class="text-gray-500 dark:text-gray-400 text-sm">Manage all your past team members or add a new alumni.</p>
          </div>
          <a type="button" href="<%= new_alumni_path %>"
                class="btn-primary">
            Add new alumni
          </a>
        </div>
      </div>
      <div class="overflow-x-auto">
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
              <th scope="col" class="px-4 py-3">Name</th>
              <th scope="col" class="px-4 py-3">Email</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
            <%= render partial: "alumni", collection: @alumnis, as: :alumni %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/alumnis/new.html.erb
<% content_for :title, "New alumni" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New alumni</h1>

  <%= render "form", alumni: @alumni %>

  <%= link_to "Back to alumnis", alumnis_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/alumnis/show.html.erb
<% content_for :title, "Showing alumni" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing alumni</h1>

  <%= render @alumni %>

  <%= link_to "Edit this alumni", edit_alumni_path(@alumni), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to alumnis", alumnis_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this alumni", @alumni, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Quick Alumni" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice = flash[:notice] %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert = flash[:alert] %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="bg-gray-800">
  <div class="mx-auto max-w-screen-2xl sm:px-6 lg:px-8">
    <div class="relative flex h-12 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
      </div>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex items-center flex-shrink-0">
          <a href="/">
            <h1 class="text-white font-extrabold font-mono">Quick Alumni</h1>
          </a>
        </div>
        <div class="hidden sm:ml-2 sm:block">
          <div class="flex space-x-1">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-500 hover:text-white" -->
            <a href=""  class="selected-nav">Alumni</a>
          </div>
        </div>
      </div>
      <div class="flex  w-96 px-2 lg:ml-6 lg:justify-end" data-behavior="autocomplete" data-controller="search" data-search-url-value="/search/candidates">
        <div class="w-full max-w-xs lg:max-w-sm justify-end">
          <div class="relative">
            <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
              <!-- Heroicon name: solid/search -->
              <svg class="w-5 h-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path>
              </svg>
            </div>
            <input id="search" name="search" class="block w-full py-1 pl-10 pr-3 leading-5 text-gray-300 placeholder-gray-400 bg-gray-700 border border-transparent rounded-xs  focus:outline-none focus:bg-white focus:border-white focus:ring-white focus:text-gray-900 sm:text-sm" placeholder="Search Alumni" type="search" data-search-target="input" autocomplete="off" spellcheck="false">
          </div>
          <div class="relative">
            <div class="absolute left-0 z-10 block w-full mt-2 origin-top-right bg-white rounded-xs shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
              <ul data-search-target="results" hidden="">
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-2 sm:pr-0">
        <a href="<%= new_alumni_path %>" class="relative rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
          <span class="absolute -inset-1.5"></span>
          <span class="sr-only">View notifications</span>
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path d="M5 12h14"/><path d="M12 5v14"/>          </svg>
        </a>
        <!-- Profile dropdown -->
        <div data-controller="dropdown" class="relative inline-block text-left">
          <div><button type="button" data-action="dropdown#toggle click@window->dropdown#hide" class="ml-2 flex text-sm bg-gray-800 rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white cursor-pointer">                     <%= image_tag "male-placeholder.png", class: "w-8 h-8 rounded-full" %>
            </button></div>
          <div data-dropdown-target="menu" class="transition transform origin-top-left absolute right-0 mt-2 w-56 z-10 rounded-xs shadow-lg bg-white shadow-lg focus:outline-none" data-transition-enter-from="opacity-0 scale-95" data-transition-enter-to="opacity-100 scale-100" data-transition-leave-from="opacity-100 scale-100" data-transition-leave-to="opacity-0 scale-95">
            <div class="py-1 ring-1 ring-gray-200 ring-opacity-5 rounded-xs">         <%= button_to "Sign Out", session_path, method: :delete, class: "w-full cursor-pointer text-left block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %>
            </div>
          </div>
        </div>
        <!-- Profile Dropdown -->
      </div>
    </div>
  </div>
</nav>